config/routes.rb
Rails.application.routes.draw do
  root "products#index"
   
  get 'orders/index' 
  get 'orders/show'
  get 'orders/new'

  # get 'products/:id' => 'products#show', as: "product"

  
  get "carts/:id" => "carts#show", as: "cart"
  delete "carts/:id" => "carts#destroy"

  
  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  devise_for :users
  resources :products
  resources :orders

  
  # get 'payment' => 'products#payment'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_items
    
    def sub_total
        sum = 0
        self.line_items.each do |line_item|
          sum+= line_item.total_price
        end
        return sum
      end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  self.table_name = "line_items"
    belongs_to :product
    belongs_to :cart
    belongs_to :order , optional: true

    def total_price
      # self.quantity *
       self.product.price
    end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items
end

app/models/product.rb
class Product < ApplicationRecord
has_many_attached :images

belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :products

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    protect_from_forgery with: :exception

    before_action :current_cart

    private
    def current_cart
      if session[:cart_id]
        cart = Cart.find_by(:id => session[:cart_id])
        if cart.present?
          @current_cart = cart
        else
          session[:cart_id] = nil
        end
      end

      if session[:cart_id] == nil
        @current_cart = Cart.create
        session[:cart_id] = @current_cart.id
      end
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy! 
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
    def create
        # Find associated product and current cart
        chosen_product = Product.find(params[:product_id])
        current_cart = @current_cart
      
        # If cart already has this product then find the relevant line_item and iterate quantity otherwise create a new line_item for this product
        if current_cart.products.include?(chosen_product)
          # Find the line_item with the chosen_product
         @line_item = current_cart.line_items.find_by(:product_id => chosen_product)
          # Iterate the line_item's quantity by one
        #  @line_item.quantity += 1
        else
         @line_item = LineItem.new
           @line_item.cart = current_cart
          @line_item.product = chosen_product
         end
      
        #  Save and redirect to cart show path
         @line_item.save!
         redirect_to cart_path(current_cart)
     end
      
      def destroy
        @line_item = LineItem.find(params[:id])
        @line_item.destroy
        redirect_to cart_path(@current_cart)
      end

      private
        def line_item_params
          params.require(:line_item).permit(:product_id, :cart_id)
        end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
     @order = Order.find(params[:id])
  end
  
  def create
    @order = Order.new(order_params)
  @current_cart.line_items.each do |item|
    @order.line_items << item
    item.cart_id = nil
  end
  @order.save
  Cart.destroy(session[:cart_id])
  session[:cart_id] = nil
  redirect_to root_path
  end
  def new
    @order = Order.new
  end
  
  private
  def order_params
    params.require(:order).permit(:name, :email, :address, :pay_method)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:update, :edit, :destroy]
 

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
    @product = Product.find(params[:id])
  end


  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
   def create
    @product = Product.new(product_params)
    @product.user = current_user

    if @product.save
      redirect_to @product, notice:"Your listing was successfully created"
    else
      render 'new'
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product = Product.find(params[:id])
  
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    product = Product.find(params[:id])
    product.destroy
    
    redirect_to products_path
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :colour, :size, :condition, :location, :price, :user_id, images:[])
    end

    def check_user
      if current_user.id != @product.user_id
        redirect_to root_url, alert: "You don't have permission to update or delete listing!"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    def product_image_url(product)
		if product.images.attached?
			url_for(product.images.first)
		else
			"https://picsum.photos/id/#{rand(1..300)}/300"
		end
	end
end

app/views/carts/show.html.erb
<br>
<h3>Cart</h2>
<br>
<ul>
  <% @cart.line_items.each do |line_item| %>
    <li>Item: <%= line_item.product.title %>/ Price: <%= number_to_currency(line_item.product.price) %>
    <%# #See lineItem section below for explanation of line_item links %>
     
      <%= link_to "Remove item", line_item_path(line_item), method: :delete %>
     
  <% end %>
</ul><br><br>
<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>
 <br>
<%= link_to "Proceed to checkout", new_order_path %><br>
<%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"} %>

app/views/layouts/_alerts.html.erb
<% flash.each do |type, msg| %>
		<div class="alert">
			<%= msg %>
		</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TakeTwoMarketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%# <nav class="navbar navbar-light" style="background-color: #e3f2fd;"> %>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> 
   <div class="container">
    <a class="logo" href="/products">TAKE TWO</a><br>
    <a class="navbar-brand" href="/products">View all listings</a>
    <a class="navbar-brand" href="/products/new">Create new listing</a>
    <a class="navbar-brand" href="/users/sign_in">Log in</a>
    <a class="navbar-brand" href="/users/sign_up">Sign up</a>
    <% if user_signed_in? %>
    <a class="navbar-brand" href="/orders">My orders</a>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%# <a class="nav-link" href="/products/new">Create new listing</a> %>
        </li>
      </ul>
    </div>
  </div>
</nav>
  <%= render 'layouts/alerts' %>
  <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
   <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% else %> 
<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
 <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<div class="container">
  <%= yield %>
</div>
<footer>
  <div class="container">
    TAKE TWO <%= Time.now.year %>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/orders/index.html.erb
<h2>My Orders</h2>

<% if user_signed_in? %>
<% @orders.each do |order| %> 
  <p>Name: <%= order.name %></p>
  <p>Email: <%= order.email %></p>
  <p>Ordered item: <% order.line_items.each do |item| %>
  <%= item.product.title %>
  <% end %>
  </p>
  <% end %>
  
<% end %> 
<%= link_to 'Back to all listings', products_path %>

app/views/orders/new.html.erb
<h3> We need your details for processing the order.<br> Please fill the form </h3>

<%= form_for(@order) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>
<%= link_to 'Changed your mind? Back to all listings', products_path %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if product.images.attached? %>
	<% product.images.each do |img| %> 
		<% image_tag img %> 
	<% end %>
  	<% end %>

  <%# <div class="container"> %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <br>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <br>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_field :colour %>
  </div>
  <br>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size %>
  </div>
  <br>


  <div class="field">
    <%= form.label :condition %>
    <%= form.text_field :condition %>
  </div>
   <br>


  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <br>


  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <br>


  <div class="field">
		<%= form.label :images %>
		<%= form.file_field :images, multiple: true %>
	</div>
  <br>

  <div class="actions">
   <%= form.submit %> 
  </div>
  <br>
  
<% end %>
</div>

app/views/products/edit.html.erb
<h1>Edit listing</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>


<h1>All clothing</h1>
<br>
<% if user_signed_in? %>
<%= link_to 'Create new listing', new_product_path %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <%# <th>Description</th> %>
      <%# <th>Colour</th> %>
      <th>Size</th>
      <%# <th>Condition</th> %>
      <th>Location</th>
      <th>Price</th>
      <br><br>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <%# <td><%= product.description</td>   %>
        <%# <td><%= product.colour</td>  %>
        <td><%= product.size %></td>
        <%# <td><%= product.condition</td>  %>
        <td><%= product.location %></td>
        <td><%= product.price %></td>
        <td><%= image_tag product_image_url(product) %></td>
        <td><%= link_to 'View more details', product_path(product) %></td>
        <%# <td><%= button_to "Add #{product.title} to cart", line_items_path(:product_id => product.id) %>
        
         <% if user_signed_in? && product.user_id == current_user.id %>
        <td><%= link_to 'Edit listing', edit_product_path(product) %></td>
        <td><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        

        
      <% end %>
      </tr>
    <% end %>
     
  </tbody>
</table>

app/views/products/new.html.erb
<h1>What are you selling today?</h1>

<%= render 'form', product: @product %> 

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<br>
<p>
  <strong>Title:</strong><br>
  <%= @product.title %>
</p>

<% if @product.images.attached? %>
	 <% @product.images.each do |img| %>
		<%= image_tag img %>
	 <% end %>
  <% else %> 
   <img src="https://picsum.photos/id/#{rand(1..300)}/200/300/"/>
 <% end %>
<br>

<p>
  <strong>Description:</strong><br>
  <%= @product.description %>
</p>

<p>
  <strong>Colour:</strong><br>
  <%= @product.colour %>
</p>

<p>
  <strong>Size:</strong><br>
  <%= @product.size %>
</p>

<p>
  <strong>Condition:</strong><br>
  <%= @product.condition %>
</p>

<p>
  <strong>Location:</strong><br>
  <%= @product.location %>
</p>

<p>
  <strong>Price:</strong><br>
  <%= @product.price %>
</p>

<% if user_signed_in? && current_user.id != @product.user_id  %>
<%# <%= link_to "Add #{product.title} to cart", line_items_path(:product_id => @product.id)  %>
<%= button_to "Add #{@product.title} to cart", line_items_path(:product_id => @product.id) %>
<%# <%= link_to 'Buy Now'%>
<% else %>
<% unless user_signed_in? && current_user.id = @product.user_id%>
<%# <%= button_to "Add #{product.title} to cart", line_items_path(:product_id => product.id) %>  
<%= button_to "Add #{@product.title} to cart", new_user_session_path %>
<%# <%= link_to 'Buy', new_user_session_path %> 
<%# <% else %> 
<%# <% if user_signed_in? && current_user.id != @product.user_id %> 
<%# <% else %>
<%# <% if user_logout? && current_user.id != @product.user_id  %> 
<%# <button type="button" class="btn btn-primary">Buy now</button>  %>
<% end %>
<% end %>

<br><br>

<%= link_to 'Edit this listing', edit_product_path(@product) %> | | |
<%= link_to 'Back to all listings', products_path %>